/*
 * File: app/model/Ocorrencia.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.model.Ocorrencia', {
    extend: 'Ext.data.Model',
    alias: 'model.ocorrencia',

    config: {
        fields: [
            {
                name: 'id_ocorrencia',
                type: 'int'
            },
            {
                name: 'id_usuario',
                type: 'int'
            },
            {           	
            	name: 'tipo_entidade',
            	type: 'char'
            },
            {
                name: 'id_entidade',
                type: 'int'
            },
            {
                name: 'data',
                type: 'date'
            },
            {
                name: 'tipo',
                type: 'char'
            },
            {
                name: 'descricao',
                type: 'string'
            }
        ],
        proxy: {
            type: 'rest',
            url : 'php/ocorrencia/post.php',
            reader: {
                type: 'json',
                rootProperty: 'ocorrencia'
            },
            writer: {
            	type: 'json',
            	rootProperty: 'ocorrencia',
                encode: true
            }
        }
    }
});